# Generated by Django 4.0 on 2021-12-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_Genre',
            new_name='album_genre',
        ),
        migrations.AddField(
            model_name='album',
            name='userid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dhun.user'),
        ),
    ]
