# Generated by Django 4.0 on 2021-12-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhun', '0002_rename_album_genre_album_album_genre_album_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhun.user'),
        ),
    ]
